In [1]:
import tensorflow as tf

In [2]:
x = tf.placeholder(tf.float32, shape= [4, 2])
y = tf.placeholder(tf.float32, shape= [4, 1])

In [3]:
w1 = tf.Variable(tf.random_uniform([2, 2]))
b1 = tf.Variable(tf.zeros([2]))
z = tf.sigmoid(tf.matmul(x, w1) + b1)

In [4]:
w2 = tf.Variable(tf.random_uniform([2, 1]))
b2 = tf.Variable(tf.zeros([1]))
y_hat = tf.sigmoid(tf.matmul(z, w2) + b2)

In [5]:
loss = tf.reduce_mean(-1 * ((y * tf.log(y_hat)) + ((1-y) * tf.log(1.0 - y_hat))))

In [6]:
train_step = tf.train.GradientDescentOptimizer(0.05).minimize(loss)

In [7]:
train_x = [[0, 0], [0, 1], [1, 0], [1, 1]]
train_y = [[0], [1], [1], [0]]

In [8]:
init = tf.global_variables_initializer()

In [9]:
with tf.Session() as sess:
    sess.run(init)
    print('train data: ', str(train_x))
    
    for i in range(20000):
        sess.run(train_step, feed_dict= {x: train_x, y: train_y})
        if i % 5000 == 0:
            print('Epoch : ', i)
            print('Output : \n', sess.run(y_hat, feed_dict= {x: train_x, y: train_y}))
    print('Fianl Output : ', sess.run(y_hat, feed_dict= {x: train_x, y: train_y}))

train data:  [[0, 0], [0, 1], [1, 0], [1, 1]]
Epoch :  0
Output : 
 [[0.60074294]
 [0.6037573 ]
 [0.6404545 ]
 [0.64284253]]
Epoch :  5000
Output : 
 [[0.38699776]
 [0.54069513]
 [0.54033864]
 [0.5658337 ]]
Epoch :  10000
Output : 
 [[0.09847254]
 [0.88303936]
 [0.8831552 ]
 [0.15737537]]
Epoch :  15000
Output : 
 [[0.0360429 ]
 [0.96930027]
 [0.9693252 ]
 [0.03551123]]
Fianl Output :  [[0.02123436]
 [0.9832368 ]
 [0.98324704]
 [0.01857951]]
